image: node:6-slim
cache:
  key: 'eslint-config-picter-node-modules'
  paths:
    - node_modules/
before_script:
  - npm config set loglevel warn
  - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
  - npm install --quiet
stages:
  - deploy
deploy:
  stage: deploy
  script:
    - npm publish
  only:
    - tags