version: 2

jobs:
  deploy_production:
    docker:
      - image: circleci/node:8.11.3
    working_directory: ~/repo
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Publish to NPM
          command: yarn publish --access public --new-version ${CIRCLE_TAG:1}

workflows:
  version: 2
  default:
    jobs:
      - deploy_production:
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+\.\d+\.\d+$/
